version: '3.8'
services:
  mongodb:
    image: mongo:6.0.14
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
    driver: local
