@TestPCS_HostAddress = http://localhost:5162

### Get All
GET {{TestPCS_HostAddress}}/products
Accept: application/json

### Get by ID
GET {{TestPCS_HostAddress}}/products/65f7f171cc5e45676768996b
Accept: application/json

### Create
POST {{TestPCS_HostAddress}}/products
Content-Type: application/json
Accept: application/json

{
  "name": "Product",
  "description": "This is the description."
}

### Upsert
PUT {{TestPCS_HostAddress}}/products/65f7f171cc5e45676768996b
Content-Type: application/json
Accept: application/json

{
  "name": "Updated Product",
  "description": "This is the updated description."
}

### Delete
DELETE {{TestPCS_HostAddress}}/products/65f7f170cc5e45676768996a
Accept: application/json
